[package]
name = "mtgql"
version = "0.1.0"
authors = ["Julia Naomi <jnaomi@thoughtworks.com>"]

[dependencies]
hyper = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
gqlog = "*"
futures = "*"
futures-cpupool = "*"
juniper = "*"
juniper_hyper = "*"
pretty_env_logger = "*"
rayon = "1.0.2"
